server:
  port: 10005
spring:
  application:
    name: project-mq
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123
      url: jdbc:mysql://localhost:3306/easybuy?serverTimezone=GMT%2B8&characterEncoding=utf8
  thymeleaf:
    cache: false
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
queue: q1
#    prefix: classpath:templates