server:
  port: 8882
spring:
  application:
    name: register-center
eureka:
  client:
    register-with-eureka: true #启动时不注册(来表示自己是一个注册中心)
    fetch-registry: true   #不从注册中心中拉取数据(表示自己是一个注册中心)
    service-url:
      defaultZone: http://localhost:8882/eureka/,http://localhost:8883/eureka/,http://localhost:8881/eureka/
  server:
    enable-self-preservation: false     #关闭自我保护


  #instance:
  #prefer-ip-address: true     #注册时用ip来注册
